---
GLOBAL:
  SERVICE: tester
  LOG:
    level: DEBUG
  ENDPOINTS:
    identity:
      v1: identity:50051
    repository:
      v1: repository:50051
    plugin:
      v1: plugin:50051    
    secret:
      v1: secret:50051
