GLOBAL:
    DATABASES:
        default:
            db: inventory
            host: mongodb
            username: inventory
            password: inventory_password

    CACHES:
        default:
            backend: spaceone.core.cache.redis_cache.RedisCache
            host: redis 
            port: 6379
            db: 0

    CONNECTORS:
        IdentityConnector:
            endpoint:
                v1: grpc://identity:50051

        PluginConnector:
            endpoint:
                v1: grpc://plugin:50051

        SecretConnector:
            endpoint:
                v1: grpc://secret:50051

        RepositoryConnector:
            endpoint:
                v1: grpc://repository:50051

    HANDLERS:
        authentication:
        - backend: spaceone.core.handler.authentication_handler.AuthenticationGRPCHandler
          uri: grpc://identity:50051/v1/Domain/get_public_key

    QUEUES:
        collector_q:
            backend: spaceone.core.queue.redis_queue.RedisQueue
            host: redis
            port: 6379
            channel: collector

        db_q:
          backend: spaceone.core.queue.redis_queue.RedisQueue
          host: redis
          port: 6379
          channel: db_upsert

    WORKERS:
      base_worker:
        backend: spaceone.core.scheduler.worker.BaseWorker
        queue: collector_q
      antman:
        backend: spaceone.inventory.scheduler.inventory_db_updater.InventoryDBUpdater
        queue: db_q
        pool: 1

    TOKEN_INFO:
        protocol: consul
        config:
            host: consul 
        uri: debug/supervisor/TOKEN

    collect_queue: collector_q
